export let Date1={
    '+':[
        {id:1,"prize":2,"Goal":5},
        {id:2,"prize":1,"Goal":2},
        {id:3,"prize":3,"Goal":7},
        {id:4,"prize":4,"Goal":12},
        {id:5,"prize":1,"Goal":2},
        {id:6,"prize":1,"Goal":2},
        {id:7,"prize":1,"Goal":2},
        {id:8,"prize":1,"Goal":2},
        {id:9,"prize":1,"Goal":2}
    ],
    '-':[
        {"prize":1,"Goal":2},
        {"prize":2,"Goal":5},
        {"prize":3,"Goal":7},
        {"prize":4,"Goal":12},
        {"prize":1,"Goal":2},
        {"prize":1,"Goal":2},
        {"prize":1,"Goal":2},
        {"prize":1,"Goal":2},
        {"prize":1,"Goal":2}
    ]
}
